"""Golden tests: fixed inputs must produce bit-identical token counts.

Golden counts are generated by running tests/golden/generate_golden.py once
and committing the resulting golden_counts.json.
"""
import json
import pytest
from pathlib import Path

from afri_fertility.tokenizers import REGISTRY
from afri_fertility.tokenizers import tiktoken_adapter  # noqa: F401
from afri_fertility.tokenizers.base import UnavailableAdapter

GOLDEN_FILE = Path(__file__).parent / "golden_counts.json"

SENTENCES = {
    "en_hello": "Hello world",
    "en_pangram": "The quick brown fox jumps over the lazy dog",
    "yor_sample": "Àwọn ará Nàìjíríà tó ń gbé ní ìlú Èkó",
    "hau_sample": "Hausa ta ci gaba da zama harshen sadarwa a Najeriya",
    "amh_sample": "አማርኛ ቋንቋ የኢትዮጵያ ብሔራዊ ቋንቋ ነው",
    "swh_sample": "Kiswahili ni lugha ya taifa ya Tanzania na Kenya",
    "fra_sample": "Le français est une langue romane parlée dans le monde entier",
    "eng_baseline": "English is the most widely used language in the world today",
}

TOKENIZERS = ["openai/o200k_base", "openai/cl100k_base"]


def _load_golden():
    if not GOLDEN_FILE.exists():
        return None
    return json.loads(GOLDEN_FILE.read_text())


@pytest.mark.parametrize("tok_id", TOKENIZERS)
@pytest.mark.parametrize("label,text", SENTENCES.items())
def test_golden_count(tok_id, label, text):
    golden = _load_golden()
    if golden is None:
        pytest.skip("golden_counts.json not yet generated — run tests/golden/generate_golden.py")

    adapter = REGISTRY.get(tok_id)
    if isinstance(adapter, UnavailableAdapter):
        pytest.skip(f"Tokenizer {tok_id} unavailable: {adapter.reason}")

    key = f"{label}__{tok_id}"
    if key not in golden:
        pytest.skip(f"Key {key} not in golden file — regenerate golden_counts.json")

    expected = golden[key]
    actual = adapter.count(text)
    assert actual == expected, (
        f"Token count mismatch for '{text}' with {tok_id}: "
        f"got {actual}, expected {expected}"
    )
